# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=10, null=True)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='piclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(blank=True, null=True, upload_to=b'piclist/%Y/%m/%d')),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pictures mobile',
            },
        ),
        migrations.AddField(
            model_name='face',
            name='pictures',
            field=models.ManyToManyField(to='hello.piclist'),
        ),
    ]
